name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: jmertic/lfx-landscape-tools@a90b284fd843ce6ed6421c15ff5c229b8f27f9ae # main
        env:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
